# Generated by Django 4.2.7 on 2025-07-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('document', models.CharField(max_length=20, verbose_name='Document (CPF/CNPJ)')),
                ('category', models.CharField(choices=[('EXEQUENTE', 'Exequente'), ('EXECUTADA', 'Executada'), ('AUTOR', 'Autor'), ('REU', 'Réu'), ('TERCEIRO', 'Terceiro'), ('ADVOGADO', 'Advogado'), ('PROCURADOR', 'Procurador')], max_length=20, verbose_name='Party Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='processes.process', verbose_name='Process')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
                'unique_together': {('process', 'name', 'document')},
            },
        ),
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=10, verbose_name='Contact Type')),
                ('value', models.CharField(max_length=255, verbose_name='Contact Value')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='parties.party', verbose_name='Party')),
            ],
            options={
                'verbose_name': 'Party Contact',
                'verbose_name_plural': 'Party Contacts',
                'ordering': ['-is_primary', 'contact_type', 'value'],
            },
        ),
    ]
