# Generated by Django 4.2.7 on 2025-07-28 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=50, unique=True, verbose_name='Process Number')),
                ('process_class', models.CharField(max_length=100, verbose_name='Process Class')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('judge', models.CharField(max_length=200, verbose_name='Judge')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['-created_at'],
            },
        ),
    ]
